### ISSUE TITLE
GPS - UTM timestamp info

### ISSUE THREAD

**Issue by gcielniak** [marc-hanheide/CallARobot#3]
There seems to be a quite long delay between the GPS and velodyne observations at the moment and there is currently no way of recovering the `right` timestamp from the GPS observation (the one reported in the NMEA string). This feature would be needed to synchronise the sensors. @marc-hanheide any ideas how to add that to the published messages? Should that replace timestamp (clients local time) or perhaps better to have both of them (e.g. gps_timestamp).

**Comment by marc-hanheide** [comment]
Hi, the timestamp should be taken from the actual GPS response and not be generated by the Ros component. I can look into this, but here's the property that should be included in the response from JavaScript:

https://developer.mozilla.org/en-US/docs/Web/API/Position/timestamp
